[project]
name = "assignment-01"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "maliksiddiq", email = "maliksiddiqawan21@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "openai-agents>=0.20.0",
    "python-dotenv>=1.2.2",
]

[project.scripts]
assignment-01 = "assignment_01:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
